global g
global d
global s
load default.mat
 if isempty(s.answer)
           s.answer{1}='[s11 s21;s21 s22]';
           for i=2:7
                s.answer{i}='[-50 0]';
          end
 end

fig = uifigure("Position",[100 100 1000 600]);
% Create list box
g.lbox = uilistbox(fig,...
    'Position',[100 100 800 400],...
    'Items',{'';},...
    'ItemsData',[0],...
    'Multiselect',"on")
%    'ValueChangedFcn', @updateEditField); 


g.label=uilabel(fig,...
     "Text","Contain string:",...
     "Position",[400 50 100 25])
g.txt_input=uitextarea(fig,...
     "value",{'High';},...
     "Position",[600 50 200 25])
g.label1=uilabel(fig,...
     "Text","Plot Format",...
     "Position",[400 25 100 25])
g.txt_input1=uitextarea(fig,...
     "value",s.answer{1},...
     "Position",[600 25 200 25])


g.btn_load=uibutton(fig,...
     "Text","Load", ...
     "Position",[800 50 50 25],...
     "ButtonPushedFcn",@(src,event) loadButtonPushed())

g.btn_plot=uibutton(fig,...
     "Text","Plot", ...
     "Position",[850 50 50 25],...
     "ButtonPushedFcn",@(src,event) plotButtonPushed())

g.btn_covert=uibutton(fig,...
     "Text","covert", ...
     "Position",[900 50 50 25],...
     "ButtonPushedFcn",@(src,event) convertButtonPushed())

g.btn_covert=uibutton(fig,...
     "Text","Config", ...
     "Position",[950 50 50 25],...
     "ButtonPushedFcn",@(src,event) configButtonPushed())




